version: "3.9"
services:
  py3:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      - LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgomp.so.1
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workdir
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8888:8888"
